### ISSUE TITLE
[FEATURE] Show hyperlink to "Go to definition"  when hovering over a symbol with pressed Ctrl/Cmd Key 

### ISSUE THREAD

**Issue by wisajkin** [cap-js/cds-intellij#28]
### Description

Normally, if you press and hold Ctrl/Cmd key and hover over a symbol, the corresponding string is converted into a hyperlink which leads to the definition when you click on it.
In CDS files the click works, but the conversion to the hyperlink doesn't.
Could you please implement it?

**Comment by tim-sh** [comment]
@wisajkin So 'the click works', i.e. leads you to the definition, and what's missing is only the hyperlink-like appearance (font underline and color)?

**Comment by tim-sh** [comment]
Hi @wisajkin, could you please share a CDS code example for the feature you are referring to and the [IDE log](https://github.com/cap-js/cds-intellij?tab=readme-ov-file#ide-logs)?

As for the log, please extract only the few lines created during your CMD+Click action or send me the file via MS Teams. Thank you!

**Comment by tim-sh** [comment]
closing as stale
