### ISSUE TITLE
[BUG] CDS syntax highlighting rarely works

### ISSUE THREAD

**Issue by Z-AK-06** [cap-js/cds-intellij#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are several developers using IntelliJ ultimate with the SAP CDS Language Support plugin 1.3.0 on Windows 11 operating system. ~When opening / editing .cds files, most of the time no support is given at all by the plugin with regards to its documented features.~[^1] For example the syntax highlighting misses out completely, ~no documentation on mouse hovering etc.~[^1] By evidence, the reported issue in https://github.com/cap-js/cds-intellij/issues/63 also appears then.

Be aware that from time to time at a sudden the plugin appears to work without any understandable reason, but most of the time it just doesn't. 

### Expected Behavior

Just expecting the documented features of the plugin to be working ... 
- Syntax highlighting
- Code completion
- Goto definition
- Hover documentation
- Document formatting
- Diagnostics
- Quick fixes

### Steps To Reproduce

Just open any .cds file in the IntelliJ environment

### Versions

SAP CDS Language Support for IntelliJ 1.3.0
We use a variety of patch levels of NodeJs v20, for example v20.18.0-win-x64, v20.16.0-win-x64, v20.11.0-win-x64

### OS / Environment

Windows

[^1]: edited, cf. https://github.com/cap-js/cds-intellij/issues/80#issuecomment-2493783611

**Comment by tim-sh** [comment]
Hello @Z-AK-06,
can you please share the [IDE logs](https://github.com/cap-js/cds-intellij#ide-logs) as a first step?
Regards, Tim

**Comment by tim-sh** [comment]
The log file sent privately by email does not seem to reveal any error. @Z-AK-06 confirmed that the other functionality mentioned was working fine after recent updates, although it remained unclear what may have caused the earlier problems. *Editing the issue description accordingly.*

**Comment by tim-sh** [comment]
@Z-AK-06 Please clarify if highlighting still seems broken.

**Comment by Z-AK-06** [comment]
Hello Tim
Indeed seems that the issue disappeared with the last environment update, so I am accordingly closing the present issue. Thanks for your support :-)
Best regards, Andreas
